### PR TITLE
Tutorial notebook template in RTD

### PR DESCRIPTION
**Pull request by lboegner**
## Summary

This PR includes a template for how we can include tutorial notebooks within our documentation, where the notebooks remain unexecuted in our repo but get built during the documentation building process. Inspired by #150 .

## Test Plan

Verified locally with:

```
cd docs
make html
```

Then opened `index.html`, clicked on the tutorial link, and verified the notebook was executed during documentation building.

TutorialNotebookScreenshot

Note: this will still need to be verified within RTD and may require further updates to the `conf.py` or requirements to resolve.

### CODE REVIEW

**Comment by lboegner** [comment]
Note: I'm not sure why the Tutorial NB tab disappeared once the NB was clicked on. At the home page, you can see it is visible on the side, but we should resolve this (at least before merging develop into main next)

Screen Shot 2023-07-23 at 7 04 16 AM

**Comment by gvanhoy** [comment]
This is the way to do it. Very, very awesome.

**Comment by lboegner** [comment]
Adding titles within the table of contents and placeholder notebooks for tutorials I could see us wanting to include.

Screen Shot 2023-07-29 at 7 29 17 AM

**Comment by lboegner** [comment]
Added a few more sub-titles in the table of contents to differentiate dataset, transform, and ML tutorials. Added sub-directories in the docs/ folder similarly.

Screen Shot 2023-07-30 at 10 38 58 AM

**Comment by gvanhoy** [comment]
There's probably more to do here, but thank you for your tremendous patience here and diligence in putting this together. Merged into v0.4.2.

**Pull request closed without merging**
